"tools/*":
  - "tool"

"components/**":
  - "frontend"

"data/**":
  - "data"

"app/**":
  - "frontend"

"hooks/**":
  - "frontend"

"lib/**":
  - "backend"

"README.md":
  - "documentation"

"CONTRIBUTING.md":
  - "documentation"
